from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

app = Flask(__name__)
app.config.from_pyfile('/data/yubei/Biotech/config.py')
db = SQLAlchemy(app)

class IGHqc(db.Model):
    __tablename__ = 'IGHqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    qc19 = db.Column(db.Integer)
    qc20 = db.Column(db.Integer)
    qc21 = db.Column(db.Integer)
    qc22 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class IGDHqc(db.Model):
    __tablename__ = 'IGDHqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class IGKqc(db.Model):
    __tablename__ = 'IGKqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class IGLqc(db.Model):
    __tablename__ = 'IGLqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class TRBVJqc(db.Model):
    __tablename__ = 'TRBVJqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    qc19 = db.Column(db.Integer)
    qc20 = db.Column(db.Integer)
    qc21 = db.Column(db.Integer)
    qc22 = db.Column(db.Integer)
    qc23 = db.Column(db.Integer)
    qc24 = db.Column(db.Integer)
    qc25 = db.Column(db.Integer)
    qc26 = db.Column(db.Integer)
    qc27 = db.Column(db.Integer)
    qc28 = db.Column(db.Integer)
    qc29 = db.Column(db.Integer)
    qc30 = db.Column(db.Integer)
    qc31 = db.Column(db.Integer)
    qc32 = db.Column(db.Integer)
    qc33 = db.Column(db.Integer)
    qc34 = db.Column(db.Integer)
    qc35 = db.Column(db.Integer)
    qc36 = db.Column(db.Integer)
    qc37 = db.Column(db.Integer)
    qc38 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class TRBDJqc(db.Model):
    __tablename__ = 'TRBDJqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    qc19 = db.Column(db.Integer)
    qc20 = db.Column(db.Integer)
    qc21 = db.Column(db.Integer)
    qc22 = db.Column(db.Integer)
    qc23 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class TRDqc(db.Model):
    __tablename__ = 'TRDqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

class TRGqc(db.Model):
    __tablename__ = 'TRGqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

if __name__ == '__main__':
    with app.app_context():
        db.drop_all()
        db.create_all()
