from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

app = Flask(__name__)
app.config.from_pyfile('/data/yubei/Biotech/config.py')
db = SQLAlchemy(app)

def serialize(self):
    json = {}
    for i in self.__table__.c:
        key = str(i.key)
        json[key] = getattr(self, key)
    return json

class IGHqc(db.Model):
    __tablename__ = 'IGHqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    qc19 = db.Column(db.Integer)
    qc20 = db.Column(db.Integer)
    qc21 = db.Column(db.Integer)
    qc22 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class IGDHqc(db.Model):
    __tablename__ = 'IGDHqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class IGKqc(db.Model):
    __tablename__ = 'IGKqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class IGLqc(db.Model):
    __tablename__ = 'IGLqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class TRBVJqc(db.Model):
    __tablename__ = 'TRBVJqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    qc19 = db.Column(db.Integer)
    qc20 = db.Column(db.Integer)
    qc21 = db.Column(db.Integer)
    qc22 = db.Column(db.Integer)
    qc23 = db.Column(db.Integer)
    qc24 = db.Column(db.Integer)
    qc25 = db.Column(db.Integer)
    qc26 = db.Column(db.Integer)
    qc27 = db.Column(db.Integer)
    qc28 = db.Column(db.Integer)
    qc29 = db.Column(db.Integer)
    qc30 = db.Column(db.Integer)
    qc31 = db.Column(db.Integer)
    qc32 = db.Column(db.Integer)
    qc33 = db.Column(db.Integer)
    qc34 = db.Column(db.Integer)
    qc35 = db.Column(db.Integer)
    qc36 = db.Column(db.Integer)
    qc37 = db.Column(db.Integer)
    qc38 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class TRBDJqc(db.Model):
    __tablename__ = 'TRBDJqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    qc19 = db.Column(db.Integer)
    qc20 = db.Column(db.Integer)
    qc21 = db.Column(db.Integer)
    qc22 = db.Column(db.Integer)
    qc23 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class TRDqc(db.Model):
    __tablename__ = 'TRDqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class TRGqc(db.Model):
    __tablename__ = 'TRGqc'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    labDate = db.Column(db.String(8), index=True)
    barcodeGroup = db.Column(db.String(10))
    labUser = db.Column(db.String(20))
    finalQCres = db.Column(db.String(4))
    posQC = db.Column(db.Float)
    posQCres = db.Column(db.String(4))
    negQC = db.Column(db.String(4))
    samplesPollute = db.Column(db.String(20))
    totalReads = db.Column(db.Integer)
    totalReadsRes = db.Column(db.String(4))
    q30 = db.Column(db.Float)
    q30Res = db.Column(db.String(4))
    primerDimers = db.Column(db.Float)
    primerDimersRes = db.Column(db.String(4))
    assembleRate = db.Column(db.Float)
    assembleRateRes = db.Column(db.String(4))
    qcRes = db.Column(db.String(4))
    qcReads = db.Column(db.Integer)
    qc1 = db.Column(db.Integer)
    qc2 = db.Column(db.Integer)
    qc3 = db.Column(db.Integer)
    qc4 = db.Column(db.Integer)
    qc5 = db.Column(db.Integer)
    qc6 = db.Column(db.Integer)
    qc7 = db.Column(db.Integer)
    qc8 = db.Column(db.Integer)
    qc9 = db.Column(db.Integer)
    qc10 = db.Column(db.Integer)
    qc11 = db.Column(db.Integer)
    qc12 = db.Column(db.Integer)
    qc13 = db.Column(db.Integer)
    qc14 = db.Column(db.Integer)
    qc15 = db.Column(db.Integer)
    qc16 = db.Column(db.Integer)
    qc17 = db.Column(db.Integer)
    qc18 = db.Column(db.Integer)
    addtime = db.Column(db.DateTime, default=datetime.now)
    
    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)

class qctohos(db.Model):
    __tablename__ = 'qctohos'
    id = db.Column(db.Integer, primary_key=True)
    qcDate = db.Column(db.String(8), index=True)
    igh = db.Column(db.String(8))
    igdh = db.Column(db.String(8))
    igk = db.Column(db.String(8))
    igl = db.Column(db.String(8))
    trbvj = db.Column(db.String(8))
    trbdj = db.Column(db.String(8))
    trg = db.Column(db.String(8))
    trd = db.Column(db.String(8))
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
    
    def to_json(self):
        return serialize(self)

class SampleInfo(db.Model):
    __tablename__ = 'sampleinfo'
    id = db.Column(db.Integer, primary_key=True)
    sampleBarcode = db.Column(db.String(50), index=True)
    projectBarcode = db.Column(db.String(20), index=True)
    projectName = db.Column(db.String(50), index=True)
    patientName = db.Column(db.String(10), index=True)
    patientID = db.Column(db.String(20), index=True)
    hospitalName = db.Column(db.String(50), index=True)
    sexName = db.Column(db.String(2))
    patientAge = db.Column(db.String(20))
    patientCardNo = db.Column(db.String(20))
    patientPhone = db.Column(db.String(20))
    sampleType = db.Column(db.String(20), index=True)
    hosDepartment = db.Column(db.String(20))
    patientNo = db.Column(db.String(20))
    bedNo = db.Column(db.String(20))
    doctorName = db.Column(db.String(20))
    clinicalDiagnosis = db.Column(db.String(100))
    sampleCollectionTime = db.Column(db.DateTime)
    sampleReceiveTime = db.Column(db.DateTime)
    diagnosisPeriod = db.Column(db.String(20), index=True)
    projectType = db.Column(db.String(20), index=True)
    reportTime = db.Column(db.DateTime)
    sampleStatus = db.Column(db.String(64), index=True)
    remark = db.Column(db.String(256))
    addtime = db.Column(db.DateTime, default=datetime.now)

    def update(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def to_json(self):
        return serialize(self)